org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true


# Dev keystore
DEV_STORE_FILE=online_grocery_dev.keystore
DEV_KEY_ALIAS=devkey
DEV_STORE_PASSWORD=devpassword
DEV_KEY_PASSWORD=devkeypassword

# Staging keystore
STG_STORE_FILE=online_grocery_staging.keystore
STG_KEY_ALIAS=stgkey
STG_STORE_PASSWORD=stgpassword
STG_KEY_PASSWORD=stgkeypassword

# Prod keystore
PROD_STORE_FILE=online_grocery_prod.keystore
PROD_KEY_ALIAS=prodkey
PROD_STORE_PASSWORD=prodpassword
PROD_KEY_PASSWORD=prodkeypassword