# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

FIREBASE_ANDROID_APP_ID = ENV["FIREBASE_ANDROID_APP_ID"]
FIREBASE_SERVICE_ACCOUNT = ENV["FIREBASE_SERVICE_ACCOUNT"]

platform :android do
  desc "Deploy online grocery androi dev to Firebase App Distribution"
  lane :distribute_android_dev_app_via_firebase do
    firebase_app_distribution(
      app: FIREBASE_ANDROID_APP_ID,
      android_artifact_path: "../build/app/outputs/flutter-apk/app-dev-release.apk",
      release_notes_file: "../app_distribution/release_notes_dev.txt",
      groups_file: "../app_distribution/dev_groups.txt",
      service_credentials_file: FIREBASE_SERVICE_ACCOUNT,
    )
  end
end
