// Mocks generated by Mockito 5.4.6 from annotations
// in online_grocery/test/domain/usecase/login_user_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:online_grocery/data/models/request/user_login_schema.dart'
    as _i7;
import 'package:online_grocery/domain/core/failures.dart' as _i5;
import 'package:online_grocery/domain/entities/user_info_entity.dart' as _i8;
import 'package:online_grocery/domain/entities/user_login_entity.dart' as _i6;
import 'package:online_grocery/domain/repositories/auth_repository.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [IAuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIAuthRepository extends _i1.Mock implements _i3.IAuthRepository {
  MockIAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.UserLoginEntity>> login(
    _i7.UserLoginSchema? userLoginSchema,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#login, [userLoginSchema]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.UserLoginEntity>>.value(
                  _FakeEither_0<_i5.Failure, _i6.UserLoginEntity>(
                    this,
                    Invocation.method(#login, [userLoginSchema]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.UserLoginEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i8.UserInfoEntity>> getUserInfo() =>
      (super.noSuchMethod(
            Invocation.method(#getUserInfo, []),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i8.UserInfoEntity>>.value(
                  _FakeEither_0<_i5.Failure, _i8.UserInfoEntity>(
                    this,
                    Invocation.method(#getUserInfo, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i8.UserInfoEntity>>);
}
